### ISSUE TITLE
:speech_balloon: Introduction To Building Web Apps using Ruby on Rails

### ISSUE THREAD

**Issue by goterpsgo** [BmoreCodeCoffee/events#1]
## About You

Joe Tseng

jtsengorg@gmail.com

Been writing software for way too long.

## Your Talk

**Title:**

Introduction To Building Web Apps using Ruby on Rails

**How long will your talk be?**
- [ ] 5-15 minutes (recommend submitting a [lightning talk](https://github.com/BmoreCodeCoffee/events/blob/main/.github/ISSUE_TEMPLATE/lightning_talk.md))
- [x] 20-30 minutes
- [ ] 30-45 minutes
- [ ] 60 minutes or more

**What will you require for your talk/presentation?**
A projector and screen

**Is there a month(s)/date(s) works best for you?**
11 Feb

**Is this practice for a talk/presentation at another event?**
- [x] Yes, and I would like feedback
- [ ] Yes, but I do not need feedback
- [ ] No

Pacing and cohesiveness
## Meta

**Do you need help crafting your talk?**
- [ ] Yes
- [x] No

**Is this presentation scheduled?**
- [ ] No
- [x] Yes (please indicate the time/date below with link to meet up event)
https://www.meetup.com/atlanta-metro-code-and-coffee/events/290440957/

**Comment by Sun-Mountain** [comment]
Completed on 02/11/2023
